spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/EdiaoZC/cloud-config.git
    bus:
      trace:
        enabled: true
  application:
    name: config-server
eureka:
  client:
    service-url:
      defaultZone: http://localhost:1001/eureka/,http://localhost:1002/eureka/
management:
  endpoints:
    web:
      exposure:
        include:
        - "*"
  endpoint:
    bus-refresh:
      enabled: true
    bus-env:
      enabled: true
server:
  port: 8088