spring:
  sleuth:
    http:
      legacy:
        enabled: true
  application:
    name: zipkin
eureka:
  client:
    service-url:
      defaultZone: http://peer1:1001/eureka/,http://peer2:1002/eureka/
server:
  port: 9090