spring:
  application:
    name: consumer-feign
eureka:
  client:
    service-url:
      defaultZone: http://peer1:1001/eureka/,http://peer2:1002/eureka/
server:
  port: 4001
management:
  endpoints:
    web:
      exposure:
        include:
        - "*"
        - hystrix.stream
feign:
  hystrix:
    enabled: true