spring:
  application:
    name: consumer-feign
eureka:
  client:
    service-url:
      defaultZone: http://peer1:1001/eureka/,http://peer2:1002/eureka/
server:
  port: 4001
feign:
  hystrix:
    enabled: true