spring:
  application:
    name: consumer-feign
  sleuth:
    http:
      legacy:
        enabled: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:1001/eureka/,http://localhost:1002/eureka/
server:
  port: 4001
management:
  endpoints:
    web:
      exposure:
        include:
        - "*"
        - hystrix.stream
feign:
  hystrix:
    enabled: true


hystrix:
  metrics:
    polling-interval-ms: 3000
  threadpool:
    movie-service:
      coreSize: 40
      maximumSize: 40
    user-service:
      coreSize: 1
      maximumSize: 5
