spring:
  application:
    name: zuul-proxy
eureka:
  client:
    service-url:
      defaultZone: http://localhost:1001/eureka/,http://localhost:1002/eureka/
server:
  port: 80
zuul:
  routes:
    user:
      serviceId: user-service
      path: /user/*
    movie:
      serviceId: movie-service
      path: /movie/*