spring:
  application:
    name: consumer-ribbon
eureka:
  client:
    service-url:
      defaultZone: http://peer1:1001/eureka/,http://peer2:1002/eureka/
server:
  port: 5001
ribbon:
  hystrix:
    enabled: true
hystrix:
  metrics:
    polling-interval-ms: 500

