spring:
  application:
    name: consumer-ribbon
  sleuth:
    http:
      legacy:
        enabled: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:1001/eureka/,http://localhost:1002/eureka/
server:
  port: 5001
ribbon:
  hystrix:
    enabled: true
hystrix:
  command:

  metrics:
    polling-interval-ms: 500


